#全局端口定义server:

spring:
  aop:
    proxy-target-class: true

# 全局字符集设置
server:
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true


aliyun:
  accessKeyId: LTAI5tCWHCcfvqQzu8k2oKmX
  secret: auoKUFsghimbfVQHpy7gtRyBkoR4vc
  #aliyun.scenes=porn,terrorism,ad,qrcode,live,logo
  scenes: terrorism

